### ISSUE TITLE
Are you talking the application on the device or pc/linux app?

### ISSUE THREAD

**Issue by awysocki** [alexvdvliet/TC421IssueTracker#4]
I have a TC421 and trying to use 5 of them on my network.  The UDP packet that searches for them only finds 2 or 3 at a time and If I try again it will be a different 2 or 3 of them.  Sometimes none.

Is there an app for Windows or Linux?  URL to download?

**Comment by alexvdvliet** [comment]
It's a windows app only

**Comment by alexvdvliet** [comment]
Maybe in the future i'll port this over onto linux. For now it's windows Only. Regarding the UDP search i know there was a bug in this area which i've resolved a while ago. try it with a new update.
